[package]
name = "cipher"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
config = { path = "../config" }
ntrulp = { version = "0.1.9", features = ["ntrup1277"] }
num_cpus = "1.16.0"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
rand_chacha = "0.3.1"
rand = "0.8.5"
