[package]
name = "zilpa-core"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/zilpay/zilpay-core"
license = "GPL-3"
authors = ["Rinat.H <hicc0rus@gmail.com>"]
resolver = "2"

[lib]
name = "shared"
path = "shared/src/lib.rs"

[workspace]
members = [
  "cipher",
  "config",
  "crypto",
  "proto",
  "shared",
  "zil_errors",
  "zilliqa",
]

[dependencies]
ethers = "2.0.14"
hex = "0.4.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
reqwest = "0.11"
serde = { version = "1.0.204", features = ["derive", "rc"] }
serde_json = "1.0.124"
sha2 = "0.10.8"
tokio = { version = "1.39.2", features = ["full", "test-util"] }
num_cpus = "1.16.0"
bip39 = "2.0.0"

[dev-dependencies]
mockito = "1.5.0"
