[package]
name = "zilpa-core"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/zilpay/zilpay-core"
license = "GPL-3"
authors = ["Rinat.H <hicc0rus@gmail.com>"]
resolver = "2"

[lib]
name = "shared"
path = "shared/src/lib.rs"

[workspace]
members = ["crypto", "proto", "shared", "zil_errors"]

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
sha2 = "0.10.8"
