[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
config = { path = "../config" }
crypto = { path = "../crypto" }
proto = { path = "../proto" }
session = { path = "../session" }
cipher = { path = "../cipher" }
num256 = "0.5.2"
bip39 = "2.0.0"
sha2 = "0.10.8"
