[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
config = { path = "../config" }
cipher = { path = "../cipher" }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.124"
