[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
config = { path = "../config" }
bincode = { path = "../bincode" }
sled = "0.34.7"
sha2 = "0.10.8"
hex = "0.4.3"
directories = "5.0.1"
