[package]
name = "zil_cc"
version = "0.1.0"
edition = "2021"

[dependencies]
elliptic-curve = "0.13.8"
hmac-drbg = "0.3.0"
k256 = "0.13.1"
secp256k1 = "0.24.0"
rand_core = "0.6.4"
sha2 = "0.10.8"
zil_errors = { path = "../zil_errors" }
