[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.6"
crypto = { path = "../crypto" }
serde = { version = "1.0.204", features = ["derive", "rc"] }
sha2 = "0.10.8"
hex = "0.4.3"

[build-dependencies]
prost-build = "0.12.6"
