[package]
name = "background"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
session = { path = "../session" }
wallet = { path = "../wallet" }
storage = { path = "../storage" }
config = { path = "../config" }
settings = { path = "../settings" }
