[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
hex = "0.4.3"
k256 = "0.13.3"
rand = "0.8.5"
sha2 = "0.10.8"
ethers = "2.0.14"
rand_chacha = "0.3.1"
